version: 2.1
orbs:
  node: circleci/node@4.3.0
  browser-tools: circleci/browser-tools@1.1.3
jobs:
  test:
    executor:
      name: node/default
      tag: '14.19.1'
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - node/install-packages:
          pkg-manager: yarn
      - run: JOBS=1 npm run lint
      - run: JOBS=1 ./node_modules/.bin/ember test
      - run: JOBS=1 ./node_modules/.bin/ember try:one ember-lts-3.16
      - run: JOBS=1 ./node_modules/.bin/ember try:one ember-release
workflows:
  tests:
    jobs:
      - test
